#==============
#  [ EXECS ]
#==============
exec-once = udiskie
exec-once = hyprsunset
exec-once = [workspace 2 silent] ghostty


#====================
# [ User Config ]
#====================
# -- ENV
# env = WLR_RENDERER, vulkan
# env = AMD_VULKAN_ICD, RADV

# -- Animations
# source = ./hypr-plugins.conf
source = ./animations/vert.conf


# -- GENERAL
# monitor = , 1920x1080@40, auto, 1
# -- -- -- -- 
# monitor = , 1680x1050@60, auto, 1

# monitor = DP-1, auto, auto, 1, mirror, eDP-1
# monitor = DP-1, 1920x1080@60, auto, 1, mirror, eDP-1

input {
  kb_layout = us
  kb_options = caps:escape
  # kb_options = caps:escape, compose:ralt
  numlock_by_default = true
}

xwayland {
  force_zero_scaling = true
}


# -- KEYBINDS 
#[ UNBINDS ]
unbind = SUPER, G
unbind = SUPER ALT, E
unbind = SUPER, V
# - - - - - - - - 

unbind = Ctrl+Alt, R
unbind = Super+Shift, C
# - - - - - - - - 

unbind = Super+Shift, S 
unbind = Super+Shift+Alt, S
# - - - - - - - - 

unbind = , Print 
unbind = Super+Shift+Alt, R
# - - - - - - - - 

#[ BINDS ]
# bind = SUPER, P, hyprexpo:expo, toggle
bind = SUPER, Backslash, exec, ~/.local/bin/nightmode
bind = SUPER, K, exec, uwsm-app -- ~/.local/bin/wayclick

bind = SUPER ALT, Return, exec, app2unit -- kitty
bind = SUPER ALT, E, exec, app2unit -- ghostty -e yazi

bind = SUPER, G, exec, app2unit -- lutris
bind = SUPER, O, exec, app2unit -- obsidian

bind = SUPER, B, exec, app2unit -- blueman-manager
bind = SUPER, V, exec, app2unit -- pavucontrol


# -- Screenshot 
bindl = SUPER, Y, exec, caelestia screenshot  # Full screen capture > clipboard
bindl = SUPER ALT, Y, exec, global, caelestia:screenshotFreeze  # Capture region (freeze)
bindl = SUPER CTRL, Y, exec, global, caelestia:screenshot  # Capture region

# -- Screen Recording 
bind = , Print, exec, caelestia record -s  # Record screen with sound
bindl = ALT, Print, exec, caelestia record -r -s   # Record region screen with sound

# -- Clipboard 
bind = SUPER, H, exec, pkill fuzzel || caelestia clipboard
bind = SUPER ALT, H, exec, cliphist wipe
bind = SUPER ALT, A, exec, hyprpicker -a  # Colour picker

# -- Kill/Restart - Caelestia Daemon
bindr = SUPER, R, exec, qs -c caelestia kill; caelestia shell -d
# bindr = CTRL SUPER, R, exec, qs -c caelestia kill; caelestia shell -d
# bindr = CTRL SUPER ALT, R, exec, qs -c caelestia kill


#[ CURSORS - DodgerBlue - Ice - Classic - Amber ]
$CSIZE = 37
$CURSOR = Bibata-Modern-Classic
exec = sleep 1 && hyprctl setcursor $CURSOR $CSIZE
exec = sleep 1 && gsettings set org.gnome.desktop.interface cursor-theme '$CURSOR'
exec = sleep 1 && gsettings set org.gnome.desktop.interface cursor-size $CSIZE

#[ GTK_THEMING ]
$GTK_THEME = adw-gtk3-dark
$ICON_THEME = Papirus-Dark
$COLOR_SCHEME = prefer-dark
exec = sleep 1 && gsettings set org.gnome.desktop.interface icon-theme $ICON_THEME
exec = sleep 1 && gsettings set org.gnome.desktop.interface gtk-theme $GTK_THEME
exec = sleep 1 && gsettings set org.gnome.desktop.interface color-scheme $COLOR_SCHEME


#====================
# [ Windows Rules]
#====================
windowrule = match:title .*\.exe, immediate on

# -- Special workspaces
windowrule = workspace special:communication, match:class com.rtosta.zapzap
windowrule = workspace special:todo, match:class obsidian

# # -- Network Manager (nmgui / nmtui)
windowrule = float true, match:class org.gnome.Loupe
windowrule = size 60% 60%, match:class org.gnome.Loupe
