# -- Set Default shell 
set -g default-shell $SHELL

set -g default-terminal "tmux-256color"
set -ga terminal-overrides ",*:Tc"

# -- enable mouse & clipboard
set -g mouse on
set -g set-clipboard on

# -- remap leader key 
unbind C-b
set -g prefix C-space
bind C-space send-prefix

# -- Start windows and panes at 1, not 0.
set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on

#[ Windows Navigation ] 
bind -n M-H previous-window
bind -n M-L next-window
# -- Pane switching with Vim keys 
bind -n M-h select-pane -L
bind -n M-j select-pane -D
bind -n M-k select-pane -U
bind -n M-l select-pane -R

#[ Open new-window in CWD ]
bind \\ new-window -c '#{pane_current_path}'
bind N new-window -c "#{pane_current_path}"
# -- open panes in current directory
bind - split-window -v -c '#{pane_current_path}'
bind / split-window -h -c '#{pane_current_path}'

#[ vi Mode ]
set-window-option -g mode-keys vi
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi C-v send-keys -X rectangle-toggle
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel

#[ TPM ]
set-environment -g TMUX_PLUGIN_MANAGER_PATH "$HOME/.local/share/tmux/plugins"

# -- plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-yank'
# - - - 

# # tmux-power theme
set -g @plugin 'wfxr/tmux-power'
set -g @tmux_power_theme 'snow' # coral - violet - snow - moon - sky - forest
set -g @tmux_power_right_arrow_icon    ''
set -g @tmux_power_left_arrow_icon     ''

set -g @tmux_power_right_w ' %T'
set -g @tmux_power_right_y ' %F'
set -g @tmux_power_right_z '#{battery_icon} #{battery_percentage}'

# tmux-battery
set -g @plugin 'tmux-plugins/tmux-battery'
set -g @batt_icon_charge_tier8 '🌕'
set -g @batt_icon_charge_tier7 '🌖'
set -g @batt_icon_charge_tier6 '🌖'
set -g @batt_icon_charge_tier5 '🌗'
set -g @batt_icon_charge_tier4 '🌗'
set -g @batt_icon_charge_tier3 '🌘'
set -g @batt_icon_charge_tier2 '🌘'
set -g @batt_icon_charge_tier1 '🌑'
set -g @batt_icon_status_charged '🔋'
set -g @batt_icon_status_charging '🔌'
set -g @batt_icon_status_discharging '💀'
set -g @batt_icon_status_attached '⚠️'
set -g @batt_icon_status_unknown '󰂑'

# Colour thresholds 
set -g @batt_color_status_primary_charged     '#3daee9'
set -g @batt_color_status_primary_charging    '#fabd2f'
set -g @batt_color_status_primary_discharging '#fb4934'
set -g @batt_color_status_primary_unknown     '#928374'


# -- Initialize TPM (keep this at the bottom)
run '$HOME/.local/share/tmux/plugins/tpm/tpm'
